config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#show"

  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :description, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_login


  def index
    @recipes = Recipe.all
  end
  
  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end


#  def create
#    @recipe = Recipe.new(recipe_params)
#
#    if @recipe.save
#      redirect_to recipe_path(@recipe), notice: "Recipe Creation Successfull"
#    else
#      @errors = @recipe.errors.full_messages
#      render :new
#    end
#  end
  def create
  new_recipe_record = current_user.recipes.new(recipe_params)
  if new_recipe_record.save
    redirect_to recipes_path notice: 'Recipe Created'
#guitar created successfully for current logged in user
  else
     #current_user.recipe.errors.full_messages
  end
end
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipes_path, notice: "Successfully Deleted: #{recipe.name}"
  end

private

  def recipe_params
    params.require(:recipe).permit(:name, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meal App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<header>
 <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= button_to 'Sign in', sign_in_path %>
    <% end %>
  </header>

  <section>
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
            <% end %>
          </div>
    <%= yield %>
  </section>
  </body>
</html>

app/views/recipes/_form.html.erb
<% if @errors.present? %>
  <div class="errors">
    <ul>
      <% @errors.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @recipe do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
 <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<div>
  <%= link_to "New Recipe", new_recipe_path %>

<div class="recipes">
  <% @recipes.each do |recipe| %>
    <div class="recipe">
      <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
      <p><%= recipe.description %></p>
      <ul class="recipe-actions">
        <li><%= link_to "Edit", edit_recipe_path(recipe) %></li>
        <li><%= link_to "Delete", recipe_path(recipe), data: {
          confirm: "Are you sure you want to delete: #{recipe.name}?",
        }, method: :delete %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render partial: "form" %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<h2>Description:</h2>
<p><%= @recipe.description %></p>

<div>
  <ul class="recipe-actions">
    <li><%= link_to "Back", recipes_path %></li>
    <li><%= link_to "Edit", edit_recipe_path(@recipe) %></li>
    <li><%= link_to "Delete", recipe_path(@recipe), data: {
      confirm: "Are you sure you want to delete: #{@recipe.name}?",
    }, method: :delete %></li>
  </ul>
</div>

app/views/welcome/show.html.erb
<h1>Say goodbye, Dockerland</h1>